#!/bin/bash
set -e
set -u
yum -y install epel-release
yum -y install ant ant-contrib make
curl --silent --location https://rpm.nodesource.com/setup_20.x | sudo bash -
yum -y install nodejs


# to run the tests
yum -y install https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
