#!/bin/bash
set -e
set -u

dnf -y install ant make
curl --silent --location https://rpm.nodesource.com/setup_20.x | sudo bash -
dnf -y install nodejs


# to run the tests
dnf -y install https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
