#!/bin/sh

set -e
set -u
set -x

printf "travis_fold:start:py-check\n"

flake8 --exclude closure -v /omero-iviewer
rst-lint /omero-iviewer/plugin/omero_iviewer/README.rst

printf "travis_fold:end:py-check\n"
